CREATE TABLE `subcontractor_bills` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `projectId` INT NOT NULL,
  `workOrderId` INT NOT NULL,
  `subcontractorId` INT NOT NULL,
  `billNo` VARCHAR(60) NOT NULL,
  `billDate` VARCHAR(20) NOT NULL,
  `periodFrom` VARCHAR(20),
  `periodTo` VARCHAR(20),
  `grossAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `retentionPct` DECIMAL(5,2) NOT NULL DEFAULT '15.00',
  `retentionAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `tdsPct` DECIMAL(5,2) NOT NULL DEFAULT '2.00',
  `tdsAmount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `otherDeductions` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `otherDeductionRemarks` TEXT,
  `netPayable` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `isFinalBill` BOOLEAN NOT NULL DEFAULT FALSE,
  `status` ENUM('Draft','Submitted','Approved','Paid') NOT NULL DEFAULT 'Draft',
  `remarks` TEXT,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sub_bills_wo` (`workOrderId`),
  INDEX `idx_sub_bills_sub` (`subcontractorId`),
  INDEX `idx_sub_bills_proj` (`projectId`)
);
CREATE TABLE `subcontractor_bill_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `billId` INT NOT NULL,
  `description` TEXT NOT NULL,
  `unit` VARCHAR(30) NOT NULL,
  `qty` DECIMAL(14,3) NOT NULL DEFAULT '0.000',
  `rate` DECIMAL(14,2) NOT NULL DEFAULT '0.00',
  `amount` DECIMAL(16,2) NOT NULL DEFAULT '0.00',
  `sortOrder` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_sub_bill_items_bill` (`billId`)
);
